# Generated by Django 2.1 on 2018-09-05 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=20)),
                ('bookauthor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookspider', models.CharField(max_length=10000)),
                ('bookname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nover.BookName')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50000, null=True)),
                ('bookspider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nover.BookSpider')),
            ],
        ),
    ]
