# Generated by Django 2.1 on 2018-09-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookspider',
            name='spider_id',
            field=models.IntegerField(default=0),
        ),
    ]
