# Generated by Django 2.1 on 2018-09-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nover', '0005_auto_20180918_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollname',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
