# Generated by Django 2.1 on 2018-09-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(max_length=20)),
                ('error_type', models.CharField(blank=True, max_length=200, null=True)),
                ('error_index', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
